License and documentation
schroeer/Nappy-Fingers pull request #4
Opened 2021-11-21 22:14 UTC by letorbi

This PR adds the GPL v3 license-file along with the according source-file-headers to the repo. Apart from that some short building instructions have been added and the Readme has been changed a bit to reflect, that the dev-team consists of two developers now.

@schroeer Since this PR changes the licensing, it would be nice if you as the original author could merge it. It just doesn't feel right when I change the license of your code ;) Also please check if the changes in the Readme are ok with you...

2021-11-22 20:36 UTC, schroeer approved these changes

2021-11-22 20:59 UTC, schroeer requested changes
Touch-menu-la and sound.js are not mine. They should be added as dependencies or rather be replaced. They are very old. In any case, we can't put them under GPL like this.

https://github.com/ericktatsui/Touch-Menu-Like-Android

I can't find the origin of sound.js anymore.

2021-11-22 21:00 UTC, schroeer approved these changes

2021-11-22 21:00 UTC, schroeer approved these changes

2021-11-22 21:01 UTC, schroeer approved these changes

2021-11-22 21:01 UTC, schroeer approved these changes

2021-11-23 21:14 UTC, letorbi commented
> Touch-menu-la and sound.js are not mine. They should be added as dependencies or rather be replaced. They are very old. In any case, we can't put them under GPL like this.

Good point. I totally missed that. I'll try to add them as dependencies...

> I can't find the origin of sound.js anymore.

I guess, it is this one: https://github.com/kittykatattack/sound.js

2021-11-24 22:55 UTC, letorbi commented
External libraries are now included as NPM dependencies. I've made the required changes for this in a separate branch, which has been merged into *master* already.

Apart form that I've also updated the about text in the app, and improved some minor things.

From my point of view the PR is ready to be merged - I hope from yours too :)

2021-12-04 19:37 UTC, merged